### ISSUE TITLE
Getting error in environment activation

### ISSUE THREAD

**Issue by bibiayisha** [qualisys/paf-opensim-example#6]
When i run this: conda env create -f environment.yml

I get the error: CondaError: Run 'conda init' before 'conda activate'

when i run conda init it does nothing, my env vars are set, everything is on right place.

**Comment by bibiayisha** [comment]
Thank you for your response. I have tried everthing again but getting the same error:
CondaError: Run 'conda init' before 'conda activate'

It creates environment but does not create it.

**Comment by AndreyAkse** [comment]
Hello again :). Did you try to activate your environment opensim_example using command line? You could try just to run python script from there using ‘Converting files from Anaconda Prompt’ guideline https://github.com/qualisys/paf-opensim-example. 
Unfortunately, we do not support python and conda environment issues as it is not our product. There could be many problems related to that, maybe you installed different versions of different python software, environment path settings etc. Would be good to look on the internet for the solution. Usually, I run this script paf-opensim-example/Templates/qtm2opensim.py in Visual Studio code but setting up and activating opensim_example environment where all libraries are installed. And you can change def main () to this code and specify where your c3d files located and run it in Visual Code or somewhere else:

def main():
    c3d_dir = r'D:\Opensim\toTRC\Data'
    for file_name in os.listdir(c3d_dir):
        if file_name.endswith('.c3d'):
            convert_c3d(c3d_dir, file_name)

if __name__ == '__main__':
    main()

Sorry, I cannot help with environment activation issue. If I had it in the past, I was deleting all python related software, reinstalling or changing in environment settings and path to python order. You can try install anaconda instead of miniconda and tick Registers as my default python for such as VSCode, pyCharm, etc. Or use another computer where you did not have any python projects.

**Comment by DocVi** [comment]
Cannot reproduced it
